home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
    :client => {
        :box_name => "centos/7",
        :ip => "192.168.50.10",
        :disks => {},
    },
    :backup => {
        :box_name => "centos/7",
        :ip => "192.168.50.15",
        :disks => {
                :sata1 => {
                    :dfile => './sata1.vdi',
                    :size => 2048,
                    :port => 1
                },
        },
    },
}

Vagrant.configure("2") do |config|
MACHINES.each do |boxname, boxconfig|
config.vm.define boxname do |box|
box.vm.box = boxconfig[:box_name]
box.vm.host_name = boxname.to_s
box.vm.network "private_network", ip: boxconfig[:ip]
box.vm.provider :virtualbox do |vb|
vb.customize ["modifyvm", :id, "--memory", "1024"]
needsController = false
boxconfig[:disks].each do |dname, dconf|
unless File.exist?(dconf[:dfile])
vb.customize ['createhd', '--filename', dconf[:dfile],
'--variant', 'Fixed', '--size', dconf[:size]]
needsController = true
end
end
if needsController == true
vb.customize ["storagectl", :id, "--name", "SATA",
"--add", "sata" ]
boxconfig[:disks].each do |dname, dconf|
vb.customize ['storageattach', :id, '--storagectl',
'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd',
'--medium', dconf[:dfile]]
end
end
end
end
end
end
