---
- hosts: central-router
  become: yes

  tasks:
  - name: 'copy static route config file'
    copy: src={{ item.src }} dest=/etc/sysconfig/network-scripts/route-{{ item.dest }}
    with_items:
      - { src: 'central-router-eth4', dest: 'eth4'}
      - { src: 'central-router-eth5', dest: 'eth5'}
    notify: restart network


  - name: 'allow forwarding'
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes


  - name: 'disable default router for eth0'
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      regexp: '^DEFROUTE='
      line: DEFROUTE="no"
    notify: restart network


  - name: 'add default route for eth6'
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth6
      regexp: '^GATEWAY='
      line: GATEWAY=192.168.0.26
    notify: restart network


  handlers:
  - name: restart network
    systemd:
      name: network
      state: restarted
