MACHINES = {
    :web => {
        :box_name => "web",
        :ip => "192.168.50.10",
    },
    :log => {
        :box_name => "log",
        :ip => "192.168.50.15",
    },
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
        box.vm.box = "centos/7"
        box.vm.box_version = "2004.01"
        box.vm.host_name = boxconfig[:box_name]
        box.vm.network "private_network", ip: boxconfig[:ip]
        box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
            needsController = false
        end
    end
end
end
