NODES = {
	:n1 => {
		:node_box  => 'ubuntu/focal64',
		:node_name => 'office1-router',
		:node_cpu  => 1,
		:node_mem  => 128,
		:node_nets => [
			{ adapter: 2, ip: '192.168.2.62', netmask: '255.255.255.192', virtualbox__intnet: 'o1-dev' },
			{ adapter: 3, ip: '192.168.2.126', netmask: '255.255.255.192', virtualbox__intnet: 'o1-srv' },
			{ adapter: 4, ip: '192.168.2.190', netmask: '255.255.255.192', virtualbox__intnet: 'o1-man' },
			{ adapter: 5, ip: '192.168.2.254', netmask: '255.255.255.192', virtualbox__intnet: 'o1-hw' },
			{ adapter: 6, ip: '192.168.0.18', netmask: '255.255.255.252', virtualbox__intnet: 'o1-c' }
		],
		:storages  => {
		}
	},
	:n2 => {
		:node_box  => 'ubuntu/focal64',
		:node_name => 'office1-server',
		:node_cpu  => 1,
		:node_mem  => 128,
		:node_nets => [
			{ adapter: 2, ip: '192.168.2.193', netmask: '255.255.255.192', virtualbox__intnet: 'o1-hw' },
		],
		:storages  => {
		}
	},
	:n3 => {
		:node_box  => 'debian/bullseye64',
		:node_name => 'office2-router',
		:node_cpu  => 1,
		:node_mem  => 128,
		:node_nets => [
			{ adapter: 2, ip: '192.168.1.126', netmask: '255.255.255.128', virtualbox__intnet: 'o2-dev' },
			{ adapter: 3, ip: '192.168.1.190', netmask: '255.255.255.192', virtualbox__intnet: 'o2-srv' },
			{ adapter: 4, ip: '192.168.1.254', netmask: '255.255.255.192', virtualbox__intnet: 'o2-hw' },
			{ adapter: 5, ip: '192.168.0.22', netmask: '255.255.255.252', virtualbox__intnet: 'o2-c' }
		],
		:storages  => {
		}
	},
	:n4 => {
		:node_box  => 'debian/bullseye64',
		:node_name => 'office2-server',
		:node_cpu  => 1,
		:node_mem  => 128,
		:node_nets => [
			{ adapter: 2, ip: '192.168.1.193', netmask: '255.255.255.192', virtualbox__intnet: 'o2-hw' },
		],
		:storages  => {
		}
	},
	:n5 => {
		:node_box  => 'centos/7',
		:node_name => 'central-router',
		:node_cpu  => 1,
		:node_mem  => 128,
		:node_nets => [
			{ adapter: 2, ip: '192.168.0.14', netmask: '255.255.255.240', virtualbox__intnet: 'c-dir' },
			{ adapter: 3, ip: '192.168.0.46', netmask: '255.255.255.240', virtualbox__intnet: 'c-hw' },
			{ adapter: 4, ip: '192.168.0.126', netmask: '255.255.255.192', virtualbox__intnet: 'c-wifi' },
			{ adapter: 5, ip: '192.168.0.17', netmask: '255.255.255.252', virtualbox__intnet: 'o1-c' },
			{ adapter: 6, ip: '192.168.0.21', netmask: '255.255.255.252', virtualbox__intnet: 'o2-c' },
			{ adapter: 7, ip: '192.168.0.25', netmask: '255.255.255.252', virtualbox__intnet: 'c-inet' }
		],
		:storages  => {
		}
	},
	:n6 => {
		:node_box  => 'centos/7',
		:node_name => 'central-server',
		:node_cpu  => 1,
		:node_mem  => 128,
		:node_nets => [
			{ adapter: 2, ip: '192.168.0.33', netmask: '255.255.255.240', virtualbox__intnet: 'c-hw' },
		],
		:storages  => {
		}
	},
	:n7 => {
		:node_box  => 'centos/7',
		:node_name => 'inet-router',
		:node_cpu  => 1,
		:node_mem  => 128,
		:node_nets => [
			{ adapter: 2, ip: '192.168.0.26', netmask: '255.255.255.252', virtualbox__intnet: 'c-inet' }
		],
		:storages  => {
		}
	}

}


Vagrant.configure("2") do |config|

	NODES.each do |node, node_config|

		config.vm.synced_folder '.', '/vagrant', type: 'rsync', rsync__exclude: ['*.vdi', '.git']

		config.vm.define node_config[:node_name] do |node|

			node.vm.box = node_config[:node_box]
			node.vm.hostname = node_config[:node_name]
			node_config[:node_nets].each do |net_config|
				node.vm.network "private_network", net_config
			end

			node.vm.provider 'virtualbox' do |vb|
				vb.name = node_config[:node_name]
				vb.cpus = node_config[:node_cpu]
				vb.memory = node_config[:node_mem]
			end
		end

		config.vm.provision node_config[:node_name], type: :ansible, playbook: "provisioning/#{node_config[:node_name]}.yml"
	end
end
